server:
  port: 8081

spring:
  cloud: 
   gateway: 
    routes:
      - id: juego
        uri: lb://juego/
        predicates:
          - Path=/juego/**
      - id: biblioteca
        uri: lb://biblioteca/
        predicates:
          - Path=/biblioteca/**
            
