server:
  port: 8081
spring:
  cloud: 
   gateway: 
    routes:
      - id: juego
        uri: juego
        predicates:
          - Path=/juego/**
      - id: biblioteca
        uri: http://localhost:8888
        predicates:
          - Path=/**
