server:
  port: 8081

spring:
  cloud: 
   gateway: 
    routes:
      - id: juego
        uri: juego
        predicates:
          - Path=/juego/**
      - id: biblioteca
        uri: biblioteca
        predicates:
          - Path=/biblioteca/**
            
