server:
  port: 8081

spring:
  cloud: 
   gateway: 
    routes:
      - id: juego
        uri: http://localhost:7777
        predicates:
          - Path=/juego/**
      - id: biblioteca
        uri: http://localhost:8888
        predicates:
          - Path=/biblioteca/**
            
